# Setup
title:               'BIGCPA'
description:         'Партнерский маркетинг, арбитраж трафика. Создание, продвижение, оптимизация сайтов и многое другое.'
tagline:             'Make Money Online'
info:                'Блог о Партнёрском маркетинге, создании сайтов и не только.'
url:                 https://bigcpa.github.io
baseurl:             ''

# About/contact
author:              Alex Creio
email:               mailcreio@gmail.com
avatar:              ava4.jpg

twitter:             https://twitter.com/acretm
disqus_shortname:    bigcpa

google-verification: 6GXUozcEfaPdh8Qcr-0qBY2AV8MkL-QoQ66FpbytieM
yandex-verification: 0454ff3fa7a92182
wmail-verification:  615e0612a1330fb09470e65c76b774af

# collections:
collections:
  tag:
    output: true
    permalink: /tag/:name/

defaults:
  -
    scope:
      path: ""
      type: tag
    values:
      layout: tag

# Navigation (2nd level links supported)
nav:
  Главнвя:
    - '/blog/'
  Заработок:
    - '/tag/money/'
  Тех. часть:
    - '/tag/jekyll/'
  Продвижение: 
    - '/tag/seo/'
  Софт и сервисы:
    - '/tag/partner/'
  Linux: 
    - '/tag/linux/'
  # Категории:           
  #   - '/cat/'
  #   - { Теги: '/tag/' }
  О блоге:          
    - '/whois/'
  Карта блога:          
    - '/tag/'
      
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jemoji
  
markdown: kramdown

excerpt_separator: "<!--more-->"

# Permalinks
paginate: 3
paginate_path: '/blog/page:num/'
permalink: '/p/:title/'

sass:
  style: compressed
  sass_dir: _scss
  
  
  
  
  
  